version: '3'

services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-7.4}-v3-fpm
    environment:
      TYPO3_VERSION: ${TYPO3_VERSION:-^10.4}
      typo3DatabaseHost: mysql
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
      ELASTICSEARCH_HOST: elasticsearch:9200
      HTTP_HOST: dummy
    depends_on:
      - elasticsearch
      - mysql
      - ssh-key
    volumes:
      - ./:/var/www/html
      - ssh-agent:/.ssh-agent

  mysql:
    image: mysql:5.7
    command:
      - mysqld
      - --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: root
    tmpfs:
      - /var/lib/mysql

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION:-7.11.2}

  ssh-agent:
    image: docksal/ssh-agent:1.3
    volumes:
      - ssh-agent:/.ssh-agent

  ssh-key:
    image: docksal/ssh-agent:1.3
    command: ['bash', '-c', 'ssh-add - </tmp/host-ssh/id_rsa']
    depends_on:
      - ssh-agent
    volumes:
      - $HOME/.ssh:/tmp/host-ssh:ro
      - ssh-agent:/.ssh-agent

volumes:
  ssh-agent:
