name: CI

on:
  push:
    branches:
     - master
    tags:
      - '*'
  pull_request:
    branches:
     - master
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 7.2
          - 7.4
        typo3:
          - ^10.4
          - ^9.5
          - ^8.7
        elasticsearch:
          - 5
          - 6.8.15
          - 7.11.2

    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          PHP_VERSION: ${{matrix.php}}
          TYPO3_VERSION: ${{matrix.typo3}}
          ELASTICSEARCH_VERSION: ${{matrix.elasticsearch}}
        run: docker-compose run --rm app composer build

      - name: Cleanup
        if: ${{ always() }}
        run: docker-compose down --volumes
